# Nom du workflow (工作流的名称)
name: Ex3 - Variables d'environnement

# Quand on pousse du code ou on fait une pull request sur la branche "ex3"
# （当有人 push 代码或发起 pull request 到 ex3 分支时触发）
on:
  push:
    branches:
      - ex3   # 这次改成 ex3 分支

jobs:  # Les tâches à exécuter (要执行的任务集合)
  afficher-message:
    runs-on: ubuntu-latest  # 执行环境 Ubuntu

    # Q1: 普通环境变量 env
    env:
      MESSAGE: "Déploiement réussi"  # (法语：部署成功)

    # Q2
    steps:
      # 显示环境变量
      - name: Afficher la variable MESSAGE
        run: echo "$MESSAGE"
