name: Ex5 - Téléchargement d'Artéfacts

on:
  push:
    branches:
      - ex5

jobs:
  generate-artifact:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Créer un fichier texte
      - name: Créer le fichier report.txt
        run: echo "Rapport d'analyse" > report.txt

      # Étape 3 : Téléverser le fichier comme artéfact
      - name: Télécharger l'artéfact
        uses: actions/upload-artifact@v4
        with:
          name: rapport-analyse
          path: report.txt
